/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using template emitter:
 *      SOM Emitter emitctm: 2.23.1.9
 */

#ifndef SOM_Module_mbfolder_Source
#define SOM_Module_mbfolder_Source
#endif
#define MbFolder_Class_Source
#define M_MbFolder_Class_Source

#include "mbfolder.ih"


SOM_Scope BOOL  SOMLINK mbfolder_wpMenuItemSelected(MbFolder *somSelf, 
                                                    HWND hwndFrame, 
                                                    ULONG ulMenuId)
{
    /* MbFolderData *somThis = MbFolderGetData(somSelf); */
    MbFolderMethodDebug("MbFolder","mbfolder_wpMenuItemSelected");

    return (MbFolder_parent_WPFolder_wpMenuItemSelected(somSelf, 
                                                        hwndFrame, 
                                                        ulMenuId));
}

SOM_Scope HWND  SOMLINK mbfolder_wpOpen(MbFolder *somSelf, HWND hwndCnr, 
                                        ULONG ulView, ULONG param)
{
    /* MbFolderData *somThis = MbFolderGetData(somSelf); */
    MbFolderMethodDebug("MbFolder","mbfolder_wpOpen");

    return (MbFolder_parent_WPFolder_wpOpen(somSelf, hwndCnr, 
                                            ulView, param));
}


SOM_Scope void  SOMLINK mbfoldercls_wpclsInitData(M_MbFolder *somSelf)
{
    /* M_MbFolderData *somThis = M_MbFolderGetData(somSelf); */
    M_MbFolderMethodDebug("M_MbFolder","mbfoldercls_wpclsInitData");

    M_MbFolder_parent_M_WPFolder_wpclsInitData(somSelf);
}

SOM_Scope void  SOMLINK mbfoldercls_wpclsUnInitData(M_MbFolder *somSelf)
{
    /* M_MbFolderData *somThis = M_MbFolderGetData(somSelf); */
    M_MbFolderMethodDebug("M_MbFolder","mbfoldercls_wpclsUnInitData");

    M_MbFolder_parent_M_WPFolder_wpclsUnInitData(somSelf);
}

