
/*
 * This file was generated by the SOM Compiler.
 * FileName: mbfolder.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.17
 *     SOM Emitter emith: 2.47
 */

/*
 * mbfolder.idl - MbFolder interface definition.
 * 
 * Converted from the SOM 1.0 precompiler format (MBFOLDER.SC, produced by
 * 'spc' 1.22 / 'emitcsc' 1.10) to SOM IDL for the modern SOM compiler (sc).
 * 
 * Original class:
 *   (C) IBM Japan / IBM Tokyo Research Laboratory, 1993, Toru Aihara.
 *   MbFolder = a WPFolder subclass that adds a menu bar to open folder
 *   views and switches icon/details views without opening new windows.
 * 
 * Conversion notes (full story in README.md):
 *   - 'class:'/'parent class:' syntax  -> 'interface X : Parent' syntax
 *   - 'override x, class;'             -> metaclass interface M_MbFolder
 *                                         with its own override list
 *   - overrides use the SOM IDL 'methodname: override;' statement form
 *     (as in all Workplace Shell / XWorkplace .idl files), NOT an
 *     'override' keyword followed by names - sc rejects that with
 *     '"override" has not been declared'
 *   - 'external prefix ='/'class prefix =' -> 'externalprefix ='
 *     ('functionprefix' additionally on the metaclass)
 *   - menu/resource IDs moved OUT of generated headers into mbids.h
 *     (they were emitted by the old precompiler; sc will not emit them)
 */


#ifndef SOM_MbFolder_h
#define SOM_MbFolder_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef MbFolder
#define MbFolder SOMObject
#endif
/*
 *  was: parent class: WPFolder
 */
#include <wpfolder.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef WPImageFile
    #define WPImageFile SOMObject
#endif /* WPImageFile */
#ifndef M_WPFileSystem
    #define M_WPFileSystem SOMObject
#endif /* M_WPFileSystem */
#ifndef M_WPFolder
    #define M_WPFolder SOMObject
#endif /* M_WPFolder */
#ifndef M_MbFolder
    #define M_MbFolder SOMObject
#endif /* M_MbFolder */

/*
 * End of bindings for IDL types.
 */

#define MbFolder_MajorVersion 1
#define MbFolder_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define MbFolderNewClass c
#pragma linkage(c, system)
#define MbFolderClassData d
#define MbFolderCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define MbFolder_classObj MbFolderClassData.classObject
#define _MbFolder MbFolder_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK MbFolderNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(MbFolderNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct MbFolderClassDataStructure {
	SOMClass *classObject;
} SOMDLINK MbFolderClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct MbFolderCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK MbFolderCClassData;

/*
 * New and Renew macros for MbFolder
 */
#define MbFolderNew() \
   ( _MbFolder ? \
	_somNew(_MbFolder) \
	: ( MbFolderNewClass(\
		MbFolder_MajorVersion, \
		MbFolder_MinorVersion),\
	   _somNew(_MbFolder)))
#define MbFolderRenew(buf) \
   ( _MbFolder ? \
	_somRenew(_MbFolder, buf) \
	: ( MbFolderNewClass(\
		MbFolder_MajorVersion, \
		MbFolder_MinorVersion),\
	   _somRenew(_MbFolder, buf)))

/*
 * Override method: wpMenuItemSelected
 */
#define MbFolder_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)

/*
 * Override method: wpOpen
 */
#define MbFolder_wpOpen(somSelf,hwndCnr,ulView,param) \
	WPObject_wpOpen(somSelf,hwndCnr,ulView,param)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define MbFolder_wpSetFldrFlags WPFolder_wpSetFldrFlags
#define MbFolder_wpQueryFldrFlags WPFolder_wpQueryFldrFlags
#define MbFolder_wpSetFldrFont WPFolder_wpSetFldrFont
#define MbFolder_wpQueryFldrFont WPFolder_wpQueryFldrFont
#define MbFolder_wpSetFldrAttr WPFolder_wpSetFldrAttr
#define MbFolder_wpQueryFldrAttr WPFolder_wpQueryFldrAttr
#define MbFolder_wpSetNextIconPos WPFolder_wpSetNextIconPos
#define MbFolder_wpQueryNextIconPos WPFolder_wpQueryNextIconPos
#define MbFolder_wpPopulate WPFolder_wpPopulate
#define MbFolder_wpQueryContent WPFolder_wpQueryContent
#define MbFolder_wpAddFolderView1Page WPFolder_wpAddFolderView1Page
#define MbFolder_wpAddFolderView2Page WPFolder_wpAddFolderView2Page
#define MbFolder_wpAddFolderView3Page WPFolder_wpAddFolderView3Page
#define MbFolder_wpAddFolderIncludePage WPFolder_wpAddFolderIncludePage
#define MbFolder_wpAddFolderSortPage WPFolder_wpAddFolderSortPage
#define MbFolder_wpAddFolderBackgroundPage WPFolder_wpAddFolderBackgroundPage
#define MbFolder_wpAddFolderMenu2Page WPFolder_wpAddFolderMenu2Page
#define MbFolder_wpAddFolderSelfClosePage WPFolder_wpAddFolderSelfClosePage
#define MbFolder_wpInitIconPosData WPFolder_wpInitIconPosData
#define MbFolder_wpFreeIconPosData WPFolder_wpFreeIconPosData
#define MbFolder_wpStoreIconPosData WPFolder_wpStoreIconPosData
#define MbFolder_wpQueryIconPosition WPFolder_wpQueryIconPosition
#define MbFolder_wpSetFldrSort WPFolder_wpSetFldrSort
#define MbFolder_wpQueryFldrSort WPFolder_wpQueryFldrSort
#define MbFolder_wpRestoreFldrRunObjs WPFolder_wpRestoreFldrRunObjs
#define MbFolder_wpStoreFldrRunObjs WPFolder_wpStoreFldrRunObjs
#define MbFolder_wpHideFldrRunObjs WPFolder_wpHideFldrRunObjs
#define MbFolder_wpDeleteContents WPFolder_wpDeleteContents
#define MbFolder_wpSetFldrDetailsClass WPFolder_wpSetFldrDetailsClass
#define MbFolder_wpQueryFldrDetailsClass WPFolder_wpQueryFldrDetailsClass
#define MbFolder_wpSearchFolder WPFolder_wpSearchFolder
#define MbFolder_wpContainsFolders WPFolder_wpContainsFolders
#define MbFolder_wpQueryOpenFolders WPFolder_wpQueryOpenFolders
#define MbFolder_wpModifyFldrFlags WPFolder_wpModifyFldrFlags
#define MbFolder_wpAddToContent WPFolder_wpAddToContent
#define MbFolder_wpDeleteFromContent WPFolder_wpDeleteFromContent
#define MbFolder_wpSetDetailsColumnVisibility WPFolder_wpSetDetailsColumnVisibility
#define MbFolder_wpIsDetailsColumnVisible WPFolder_wpIsDetailsColumnVisible
#define MbFolder_wpSetFldrSortClass WPFolder_wpSetFldrSortClass
#define MbFolder_wpQueryFldrSortClass WPFolder_wpQueryFldrSortClass
#define MbFolder_wpSetSortAttribAvailable WPFolder_wpSetSortAttribAvailable
#define MbFolder_wpIsSortAttribAvailable WPFolder_wpIsSortAttribAvailable
#define MbFolder_wpQueryIconViewPos WPFolder_wpQueryIconViewPos
#define MbFolder_wpAddFirstChild WPFolder_wpAddFirstChild
#define MbFolder_wpFlushNotifications WPFolder_wpFlushNotifications
#define MbFolder_wpSetMenuBarVisibility WPFolder_wpSetMenuBarVisibility
#define MbFolder_wpQueryMenuBarVisibility WPFolder_wpQueryMenuBarVisibility
#define MbFolder_wpQueryIconTextBackgroundColor WPFolder_wpQueryIconTextBackgroundColor
#define MbFolder_wpSetIconTextBackgroundColor WPFolder_wpSetIconTextBackgroundColor
#define MbFolder_wpQueryIconTextColor WPFolder_wpQueryIconTextColor
#define MbFolder_wpSetIconTextColor WPFolder_wpSetIconTextColor
#define MbFolder_wpQueryShadowTextColor WPFolder_wpQueryShadowTextColor
#define MbFolder_wpSetShadowTextColor WPFolder_wpSetShadowTextColor
#define MbFolder_wpQueryIconTextVisibility WPFolder_wpQueryIconTextVisibility
#define MbFolder_wpSetIconTextVisibility WPFolder_wpSetIconTextVisibility
#define MbFolder_wpQueryFldrBackground WPFolder_wpQueryFldrBackground
#define MbFolder_wpSetFldrBackground WPFolder_wpSetFldrBackground
#define MbFolder_wpInitData WPObject_wpInitData
#define MbFolder_wpUnInitData WPObject_wpUnInitData
#define MbFolder_wpFree WPObject_wpFree
#define MbFolder_wpDelete WPObject_wpDelete
#define MbFolder_wpConfirmDelete WPObject_wpConfirmDelete
#define MbFolder_wpSaveState WPObject_wpSaveState
#define MbFolder_wpRestoreState WPObject_wpRestoreState
#define MbFolder_wpAddSettingsPages WPObject_wpAddSettingsPages
#define MbFolder_wpSetup WPObject_wpSetup
#define MbFolder_wpMoveObject WPObject_wpMoveObject
#define MbFolder_wpDrop WPObject_wpDrop
#define MbFolder_wpDragOver WPObject_wpDragOver
#define MbFolder_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define MbFolder_wpAddFile3Page WPFileSystem_wpAddFile3Page
#define MbFolder_wpAddFile2Page WPFileSystem_wpAddFile2Page
#define MbFolder_wpFormatDragItem WPObject_wpFormatDragItem
#define MbFolder_wpRender WPObject_wpRender
#define MbFolder_wpRefresh WPFileSystem_wpRefresh
#define MbFolder_wpQueryDefaultView WPObject_wpQueryDefaultView
#define MbFolder_wpRenderComplete WPObject_wpRenderComplete
#define MbFolder_wpAddFileMenuPage WPFileSystem_wpAddFileMenuPage
#define MbFolder_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define MbFolder_wpObjectReady WPObject_wpObjectReady
#define MbFolder_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define MbFolder_wpModifyMenu WPObject_wpModifyMenu
#define MbFolder_wpFilterMenu WPObject_wpFilterMenu
#define MbFolder_wpDisplayMenu WPObject_wpDisplayMenu
#define MbFolder_somDefaultInit SOMObject_somDefaultInit
#define MbFolder_somDestruct SOMObject_somDestruct
#define MbFolder_wpSetIconData WPObject_wpSetIconData
#define MbFolder_wpSetRealName WPFileSystem_wpSetRealName
#define MbFolder_wpSetType WPFileSystem_wpSetType
#define MbFolder_wpQueryType WPFileSystem_wpQueryType
#define MbFolder_wpSetAttr WPFileSystem_wpSetAttr
#define MbFolder_wpQueryAttr WPFileSystem_wpQueryAttr
#define MbFolder_wpAddFile1Page WPFileSystem_wpAddFile1Page
#define MbFolder_wpQueryCreation WPFileSystem_wpQueryCreation
#define MbFolder_wpQueryLastAccess WPFileSystem_wpQueryLastAccess
#define MbFolder_wpQueryLastWrite WPFileSystem_wpQueryLastWrite
#define MbFolder_wpQueryFileSize WPFileSystem_wpQueryFileSize
#define MbFolder_wpQueryEASize WPFileSystem_wpQueryEASize
#define MbFolder_wpSetDateInfo WPFileSystem_wpSetDateInfo
#define MbFolder_wpSetFileSizeInfo WPFileSystem_wpSetFileSizeInfo
#define MbFolder_wpQueryRefreshFlags WPFileSystem_wpQueryRefreshFlags
#define MbFolder_wpSetRefreshFlags WPFileSystem_wpSetRefreshFlags
#define MbFolder_wpPrintPlainTextFile WPFileSystem_wpPrintPlainTextFile
#define MbFolder_wpSetTitleAndRenameFile WPFileSystem_wpSetTitleAndRenameFile
#define MbFolder_wpConfirmRenameFileWithExt WPFileSystem_wpConfirmRenameFileWithExt
#define MbFolder_wpVerifyUpdateAccess WPFileSystem_wpVerifyUpdateAccess
#define MbFolder_wpQueryEASupport WPFileSystem_wpQueryEASupport
#define MbFolder_wpAddUserItemsToPopupMenu WPFileSystem_wpAddUserItemsToPopupMenu
#define MbFolder_wpIsDiskSwapped WPFileSystem_wpIsDiskSwapped
#define MbFolder_wpQueryRealName WPFileSystem_wpQueryRealName
#define MbFolder_wpQueryFilename WPFileSystem_wpQueryFilename
#define MbFolder_wpQueryDisk WPFileSystem_wpQueryDisk
#define MbFolder_wpQueryDateInfo WPFileSystem_wpQueryDateInfo
#define MbFolder_wpConfirmKeepAssoc WPFileSystem_wpConfirmKeepAssoc
#define MbFolder_wpQueryFileSizeL WPFileSystem_wpQueryFileSizeL
#define MbFolder_wpSetFileSizeL WPFileSystem_wpSetFileSizeL
#define MbFolder_wpQueryHandle WPObject_wpQueryHandle
#define MbFolder_wpSaveImmediate WPObject_wpSaveImmediate
#define MbFolder_wpSetTitle WPObject_wpSetTitle
#define MbFolder_wpViewObject WPObject_wpViewObject
#define MbFolder_wpSwitchTo WPObject_wpSwitchTo
#define MbFolder_wpCopyObject WPObject_wpCopyObject
#define MbFolder_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define MbFolder_wpQueryIcon WPObject_wpQueryIcon
#define MbFolder_wpQueryIconData WPObject_wpQueryIconData
#define MbFolder_wpQueryDetailsData WPObject_wpQueryDetailsData
#define MbFolder_wpDraggedOverObject WPObject_wpDraggedOverObject
#define MbFolder_wpDroppedOnObject WPObject_wpDroppedOnObject
#define MbFolder_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define MbFolder_wpAppendObject WPObject_wpAppendObject
#define MbFolder_wpReplaceObject WPObject_wpReplaceObject
#define MbFolder_wpQueryStyle WPObject_wpQueryStyle
#define MbFolder_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define MbFolder_wpIdentify WPObject_wpIdentify
#define MbFolder_wpIsDeleteable WPObject_wpIsDeleteable
#define MbFolder_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define MbFolder_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define MbFolder_wpAddToObjUseList WPObject_wpAddToObjUseList
#define MbFolder_wpAllocMem WPObject_wpAllocMem
#define MbFolder_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define MbFolder_wpClose WPObject_wpClose
#define MbFolder_wpCnrInsertObject WPObject_wpCnrInsertObject
#define MbFolder_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define MbFolder_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define MbFolder_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define MbFolder_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define MbFolder_wpCreateAnother WPObject_wpCreateAnother
#define MbFolder_wpCreateShadowObject WPObject_wpCreateShadowObject
#define MbFolder_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define MbFolder_wpDisplayHelp WPObject_wpDisplayHelp
#define MbFolder_wpEndConversation WPObject_wpEndConversation
#define MbFolder_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define MbFolder_wpFindUseItem WPObject_wpFindUseItem
#define MbFolder_wpFreeMem WPObject_wpFreeMem
#define MbFolder_wpHide WPObject_wpHide
#define MbFolder_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define MbFolder_wpInsertMenuItems WPObject_wpInsertMenuItems
#define MbFolder_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define MbFolder_wpModifyPopupMenu WPObject_wpModifyPopupMenu
#define MbFolder_wpPrintObject WPObject_wpPrintObject
#define MbFolder_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define MbFolder_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define MbFolder_wpQueryConfirmations WPObject_wpQueryConfirmations
#define MbFolder_wpQueryError WPObject_wpQueryError
#define MbFolder_wpSetFolder WPObject_wpSetFolder
#define MbFolder_wpQueryFolder WPObject_wpQueryFolder
#define MbFolder_wpQueryMinWindow WPObject_wpQueryMinWindow
#define MbFolder_wpSetTaskRec WPObject_wpSetTaskRec
#define MbFolder_wpFindTaskRec WPObject_wpFindTaskRec
#define MbFolder_wpQueryTitle WPObject_wpQueryTitle
#define MbFolder_wpRegisterView WPObject_wpRegisterView
#define MbFolder_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define MbFolder_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define MbFolder_wpRestore WPObject_wpRestore
#define MbFolder_wpRestoreData WPObject_wpRestoreData
#define MbFolder_wpRestoreLong WPObject_wpRestoreLong
#define MbFolder_wpRestoreString WPObject_wpRestoreString
#define MbFolder_wpSaveData WPObject_wpSaveData
#define MbFolder_wpSaveDeferred WPObject_wpSaveDeferred
#define MbFolder_wpSaveLong WPObject_wpSaveLong
#define MbFolder_wpSaveString WPObject_wpSaveString
#define MbFolder_wpScanSetupString WPObject_wpScanSetupString
#define MbFolder_wpSetConcurrentView WPObject_wpSetConcurrentView
#define MbFolder_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define MbFolder_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define MbFolder_wpSetDefaultView WPObject_wpSetDefaultView
#define MbFolder_wpSetError WPObject_wpSetError
#define MbFolder_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define MbFolder_wpSetupOnce WPObject_wpSetupOnce
#define MbFolder_wpSetIcon WPObject_wpSetIcon
#define MbFolder_wpSetMinWindow WPObject_wpSetMinWindow
#define MbFolder_wpModifyStyle WPObject_wpModifyStyle
#define MbFolder_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define MbFolder_wpUnlockObject WPObject_wpUnlockObject
#define MbFolder_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define MbFolder_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define MbFolder_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define MbFolder_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define MbFolder_wpSetObjectID WPObject_wpSetObjectID
#define MbFolder_wpQueryObjectID WPObject_wpQueryObjectID
#define MbFolder_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define MbFolder_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define MbFolder_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define MbFolder_wpFindViewItem WPObject_wpFindViewItem
#define MbFolder_wpLockObject WPObject_wpLockObject
#define MbFolder_wpIsLocked WPObject_wpIsLocked
#define MbFolder_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define MbFolder_wpWaitForClose WPObject_wpWaitForClose
#define MbFolder_wpSetMenuStyle WPObject_wpSetMenuStyle
#define MbFolder_wpQueryMenuStyle WPObject_wpQueryMenuStyle
#define MbFolder_wpSetStyle WPObject_wpSetStyle
#define MbFolder_somInit SOMObject_somInit
#define MbFolder_somUninit SOMObject_somUninit
#define MbFolder_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define MbFolder_somDefaultAssign SOMObject_somDefaultAssign
#define MbFolder_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define MbFolder_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define MbFolder_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define MbFolder_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define MbFolder_somDefaultVAssign SOMObject_somDefaultVAssign
#define MbFolder_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define MbFolder_somFree SOMObject_somFree
#define MbFolder_somGetClass SOMObject_somGetClass
#define MbFolder_somGetClassName SOMObject_somGetClassName
#define MbFolder_somGetSize SOMObject_somGetSize
#define MbFolder_somIsA SOMObject_somIsA
#define MbFolder_somIsInstanceOf SOMObject_somIsInstanceOf
#define MbFolder_somRespondsTo SOMObject_somRespondsTo
#define MbFolder_somDispatch SOMObject_somDispatch
#define MbFolder_somClassDispatch SOMObject_somClassDispatch
#define MbFolder_somCastObj SOMObject_somCastObj
#define MbFolder_somResetObj SOMObject_somResetObj
#define MbFolder_somDispatchV SOMObject_somDispatchV
#define MbFolder_somDispatchL SOMObject_somDispatchL
#define MbFolder_somDispatchA SOMObject_somDispatchA
#define MbFolder_somDispatchD SOMObject_somDispatchD
#define MbFolder_somPrintSelf SOMObject_somPrintSelf
#define MbFolder_somDumpSelf SOMObject_somDumpSelf
#define MbFolder_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_MbFolder_h */

#ifndef SOM_M_MbFolder_h
#define SOM_M_MbFolder_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_MbFolder
#define M_MbFolder SOMObject
#endif
/*
 *  metaclass: holds the wpcls* overrides
 */
#include <wpfolder.h>

/*
 * Start of bindings for IDL types
 */


/*
 * End of bindings for IDL types.
 */

#define M_MbFolder_MajorVersion 0
#define M_MbFolder_MinorVersion 0

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_MbFolderNewClass c
#pragma linkage(c, system)
#define M_MbFolderClassData d
#define M_MbFolderCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_MbFolder_classObj M_MbFolderClassData.classObject
#define _M_MbFolder M_MbFolder_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_MbFolderNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_MbFolderNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_MbFolderClassDataStructure {
	SOMClass *classObject;
} SOMDLINK M_MbFolderClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_MbFolderCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_MbFolderCClassData;

/*
 * New and Renew macros for M_MbFolder
 */
#define M_MbFolderNew() \
   ( _M_MbFolder ? \
	_somNew(_M_MbFolder) \
	: ( M_MbFolderNewClass(\
		M_MbFolder_MajorVersion, \
		M_MbFolder_MinorVersion),\
	   _somNew(_M_MbFolder)))
#define M_MbFolderRenew(buf) \
   ( _M_MbFolder ? \
	_somRenew(_M_MbFolder, buf) \
	: ( M_MbFolderNewClass(\
		M_MbFolder_MajorVersion, \
		M_MbFolder_MinorVersion),\
	   _somRenew(_M_MbFolder, buf)))

/*
 * Override method: wpclsInitData
 */
#define M_MbFolder_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsUnInitData
 */
#define M_MbFolder_wpclsUnInitData(somSelf) \
	M_WPObject_wpclsUnInitData(somSelf)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_MbFolder_wpclsQueryIconDataN M_WPFolder_wpclsQueryIconDataN
#define M_MbFolder_wpclsQueryIconN M_WPFolder_wpclsQueryIconN
#define M_MbFolder_wpclsQueryOpenFolders M_WPFolder_wpclsQueryOpenFolders
#define M_MbFolder_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_MbFolder_wpclsQueryTitle M_WPObject_wpclsQueryTitle
#define M_MbFolder_wpclsQueryIconData M_WPObject_wpclsQueryIconData
#define M_MbFolder_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_MbFolder_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_MbFolder_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_MbFolder_wpclsQueryAwakeObject M_WPFileSystem_wpclsQueryAwakeObject
#define M_MbFolder_wpclsFileSysExists M_WPFileSystem_wpclsFileSysExists
#define M_MbFolder_wpclsQueryObjectFromPath M_WPFileSystem_wpclsQueryObjectFromPath
#define M_MbFolder_wpclsQueryInstanceType M_WPFileSystem_wpclsQueryInstanceType
#define M_MbFolder_wpclsQueryInstanceFilter M_WPFileSystem_wpclsQueryInstanceFilter
#define M_MbFolder_wpclsQueryInstanceClass M_WPFileSystem_wpclsQueryInstanceClass
#define M_MbFolder_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_MbFolder_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_MbFolder_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_MbFolder_wpclsNew M_WPObject_wpclsNew
#define M_MbFolder_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_MbFolder_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_MbFolder_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_MbFolder_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_MbFolder_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_MbFolder_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_MbFolder_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_MbFolder_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_MbFolder_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_MbFolder_wpclsSetError M_WPObject_wpclsSetError
#define M_MbFolder_wpclsQueryError M_WPObject_wpclsQueryError
#define M_MbFolder_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_MbFolder_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_MbFolder_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_MbFolder_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_MbFolder_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_MbFolder_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_MbFolder_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_MbFolder_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_MbFolder_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_MbFolder_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_MbFolder_somUninit SOMObject_somUninit
#define M_MbFolder_somClassReady SOMClass_somClassReady
#define M_MbFolder_somNew SOMClass_somNew
#define M_MbFolder_somRenew SOMClass_somRenew
#define M_MbFolder__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_MbFolder__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_MbFolder__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_MbFolder_somNewNoInit SOMClass_somNewNoInit
#define M_MbFolder_somRenewNoInit SOMClass_somRenewNoInit
#define M_MbFolder_somRenewNoZero SOMClass_somRenewNoZero
#define M_MbFolder_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_MbFolder_somAllocate SOMClass_somAllocate
#define M_MbFolder_somDeallocate SOMClass_somDeallocate
#define M_MbFolder_somInitClass SOMClass_somInitClass
#define M_MbFolder_somInitMIClass SOMClass_somInitMIClass
#define M_MbFolder_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_MbFolder_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_MbFolder_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_MbFolder_somGetApplyStub SOMClass_somGetApplyStub
#define M_MbFolder_somGetClassData SOMClass_somGetClassData
#define M_MbFolder_somSetClassData SOMClass_somSetClassData
#define M_MbFolder_somGetClassMtab SOMClass_somGetClassMtab
#define M_MbFolder_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_MbFolder_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_MbFolder_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_MbFolder_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_MbFolder_somGetMemberToken SOMClass_somGetMemberToken
#define M_MbFolder_somGetMethodData SOMClass_somGetMethodData
#define M_MbFolder_somGetRdStub SOMClass_somGetRdStub
#define M_MbFolder_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_MbFolder_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_MbFolder_somGetMethodToken SOMClass_somGetMethodToken
#define M_MbFolder_somGetName SOMClass_somGetName
#define M_MbFolder_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_MbFolder_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_MbFolder_somGetNumMethods SOMClass_somGetNumMethods
#define M_MbFolder_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_MbFolder_somGetParent SOMClass_somGetParent
#define M_MbFolder_somGetParents SOMClass_somGetParents
#define M_MbFolder_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_MbFolder_somFindMethod SOMClass_somFindMethod
#define M_MbFolder_somFindMethodOk SOMClass_somFindMethodOk
#define M_MbFolder_somFindSMethod SOMClass_somFindSMethod
#define M_MbFolder_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_MbFolder_somLookupMethod SOMClass_somLookupMethod
#define M_MbFolder_somCheckVersion SOMClass_somCheckVersion
#define M_MbFolder_somDescendedFrom SOMClass_somDescendedFrom
#define M_MbFolder_somSupportsMethod SOMClass_somSupportsMethod
#define M_MbFolder_somDefinedMethod SOMClass_somDefinedMethod
#define M_MbFolder_somOverrideMtab SOMClass_somOverrideMtab
#define M_MbFolder_somDefaultInit SOMObject_somDefaultInit
#define M_MbFolder_somDestruct SOMObject_somDestruct
#define M_MbFolder_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_MbFolder_somDefaultAssign SOMObject_somDefaultAssign
#define M_MbFolder_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_MbFolder_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_MbFolder_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_MbFolder_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_MbFolder_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_MbFolder_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_MbFolder_somInit SOMObject_somInit
#define M_MbFolder_somFree SOMObject_somFree
#define M_MbFolder_somGetClass SOMObject_somGetClass
#define M_MbFolder_somGetClassName SOMObject_somGetClassName
#define M_MbFolder_somGetSize SOMObject_somGetSize
#define M_MbFolder_somIsA SOMObject_somIsA
#define M_MbFolder_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_MbFolder_somRespondsTo SOMObject_somRespondsTo
#define M_MbFolder_somDispatch SOMObject_somDispatch
#define M_MbFolder_somClassDispatch SOMObject_somClassDispatch
#define M_MbFolder_somCastObj SOMObject_somCastObj
#define M_MbFolder_somResetObj SOMObject_somResetObj
#define M_MbFolder_somDispatchV SOMObject_somDispatchV
#define M_MbFolder_somDispatchL SOMObject_somDispatchL
#define M_MbFolder_somDispatchA SOMObject_somDispatchA
#define M_MbFolder_somDispatchD SOMObject_somDispatchD
#define M_MbFolder_somPrintSelf SOMObject_somPrintSelf
#define M_MbFolder_somDumpSelf SOMObject_somDumpSelf
#define M_MbFolder_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_MbFolder_h */
